#!/bin/sh

current=$(xrandr --prop --verbose | grep -A10 " connected" | grep "Brightness")
current=${current##*: }
query=$(printf '%s' "$*")

case "$query" in (-*) query=${query##*-}; number=$(bc <<< "$current - $query"); xrandr --output eDP-1 --brightness $number ; esac
case "$query" in (+*) query=${query##*+}; number=$(bc <<< "$current + $query"); xrandr --output eDP-1 --brightness $number ; esac
case "$query" in (current) echo ${current##*: } ; esac
