#!/bin/sh
# vim:foldmethod=marker


# setbg, an easy script for my dwm build.
# tweaked/added code from bugswriters script of the same name

alias wal=$HOME/.local/bin/wal

#: Functions {{{

main() {
  echo $wall
  echo "Setting up wallpaper..."
  sed -i d $HOME/.cache/setbg/setbg.cache
  echo $wall > $HOME/.cache/setbg/setbg.cache
  xwallpaper --zoom $wall
  echo "Generating pywal colorschemes..."
  wal --backend schemer2 -q -i $wall
  killall dunst
  exec dunst & 2>&1
  ext=$(echo ${wall##*/})
  ext=$(echo ${ext##*.})
  rm $HOME/Projects/html_clock/assets/image.*
  ln -s $wall $HOME/Projects/html_clock/assets/image.$ext
}

# stolen from dylanaraps pfetch
has() {
  _cmd=$(command -v "$1") 2>/dev/null || return 1
  [ -x "$_cmd" ] || return 1
}

#: }}}

#: Case Statement {{{

case $* in
  (-h*|--help*)
    printf '%s\n' "
flags:
  -h|--help  display help text
  -s         choose specific background using sxiv
             choose wallpaper by hitting m and q to quit
       if multiple wallpapers are chosen, one will
             be randomly chosen out of the n amount of them
  -l         use last used wallpaper
  -d         use specific wallpaper without using -s ex. 'setbg -d ./wall.png'
  "
  ;;
  (-s)
    if has sxiv;then
      wall=$(sxiv -tpfo -z 200 $HOME/.wallpapers | tr ' ' '\n' | shuf -n 1) # you are able to choose multiple wallpapers which then are
      if [ -z "$wall" ];then # checks to see if no wallpapers were chosen   ## randomly selected between n amount, and you can just choose one.
        echo "no wallpapers selected!"
        exit 0
      else
        main
      fi
    else
        echo "sxiv not installed, please install it to use this flag"
	echo "arch: sudo pacman -S sxiv\ndebian: sudo apt install sxiv"
    fi
  ;;
   (-d*)
    wall=$@
    wall=$(echo $wall | sed 's/-d //')
    if [ -z "$wall" ];then
      echo "no wallpapers selected!"
      exit 1
    else
      main 
    fi
  ;;
  (-l)
    echo "Using Last Wallpaper Used..."
    wall=$(cat $HOME/.cache/setbg/setbg.cache)
    if [ -z "$wall" ];then
        echo "no wallpaper found..."
	echo "if there is a wallpaper in the cache, please open a issue/pr"
	exit 0
    else
	echo $wall
        xwallpaper --zoom $wall
        wal --backend schemer2 -i $wall >/dev/null
    fi
  ;;
  (*)
    echo "Choosing Random Wallpaper..."
    wall=$(find $HOME/.wallpapers -type f | shuf -n 1)
    echo ${wall##*/}
    main
  ;;
esac
#: }}}
